### ISSUE TITLE
Chore: Project setup

### ISSUE THREAD

**Issue by jkarenzi** [jkarenzi/task-master-be#1]
### Description

Set up base project with all necessary dependencies and non-technical tools

### Tasks

- [x] Set up empty express project, with basic dependencies
- [x] Set up CI/CD
- [x] Set up test environment using jest & code coverage
- [x] Set up swagger documentation for the project
- [x] Set up global error handler
- [x] Write comprehensive README file for project
- [x] Dockerize the project

### Definition of Done

- Express project is fully setup and deployed
