### ISSUE TITLE
Feat: Implement sprint/milestone functionality

### ISSUE THREAD

**Issue by jkarenzi** [jkarenzi/task-master-be#12]
### Description

- As a user, I want to be able to create a new sprint/milestone to help me keep track of my tasks

### Tasks
- [ ] Implement crud operations on sprint/milestone
- [ ] Write appropriate tests
- [ ] Write swagger documentation for resulting endpoints

### Definition of Done
- User is able to create a new sprint/milestone
- User is able to add tasks into the milestone
- User is able to close/reopen the milestone
