### ISSUE TITLE
Feat: Manage Profile Information

### ISSUE THREAD

**Issue by jkarenzi** [jkarenzi/task-master-be#13]
### Description

- As a user, I want to be able to manage my profile information. i.e change my email, change my password, change my profile picture.
- As an admin, I want to be able to manage users by getting all users, and deleting users

### Tasks
- [ ] Implement endpoints for changing email,password and profile picture
- [ ] Implement protected endpoints for managing users
- [ ] Write appropriate tests
- [ ] Write swagger documentation for resulting endpoints

### Definition of Done
- User is able to change their password, email and profile picture
- Admin is able to manage users
