### ISSUE TITLE
Feat: Authentication and Authorization

### ISSUE THREAD

**Issue by jkarenzi** [jkarenzi/task-master-be#2]
### Description/Stories

- As a task management platform, we want to be able to enforce role-based access control throughout the application, so that a user is able to access only what they should, at a given time.

- As a user, I want to be able to create a new account, and also log into the application

### Tasks

- [ ] Set up endpoints for user sign up and login
- [ ] Define roles and permissions for normal users and admins
- [ ] Implement an API endpoint for managing roles and permissions, and assigning new roles to users
- [ ] Enforce role-based access control throughout the application
- [ ] Implement appropriate error handling and responses
- [ ] Write comprehensive unit tests

### Definition of Done

- user can create a new account and log into the application
- admin can manage roles, and assign them to users
- Comprehensive unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation for the resulting endpoints is completed
