### ISSUE TITLE
Feat: CRUD Task, Label, Board, Category

### ISSUE THREAD

**Issue by jkarenzi** [jkarenzi/task-master-be#3]
### Description

As a user, I want to be able to create a new task, update an existing task, get all my tasks, and delete a task.
As a user, I want to be able to create a new board, get all my boards and delete an existing board.
As a user, I want to be able to create a new label, get, update and delete label

### Tasks

- [ ] Implement endpoints for creating, getting, updating and deleting tasks
- [ ] Implement endpoints related to managing labels
- [ ] Implement endpoints related to managing boards
- [ ] Write appropriate documentation for resulting endpoints
- [ ] Implement appropriate error handling and responses
- [ ] Write comprehensive unit tests

### Developer Notes

- tasks should have a name, description(incorporate markdown syntax), labels, and bg-color
- labels should have a name, a color and the user who created them.
- boards should have a name, short description, and the user who created them.

### Definition of Done

- User is able to create,get, update and delete tasks
- User is able to create, get, update and assign labels to their tasks
- User is able to add, get and delete boards
- User is able to style tasks with colors
- Comprehensive unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation for the resulting endpoints is completed
