### ISSUE TITLE
Feat: Email verification and Two factor Authentication

### ISSUE THREAD

**Issue by jkarenzi** [jkarenzi/task-master-be#4]
### Description/Stories

- As a user, I want to be able to verify my email after signing up, so that am able to use all the features of the application
- As a user, I want to be able to activate two factor authentication as an additional step in the login process.

### Tasks

- [ ] Email integration with mailgun or any other provider
- [ ] Implement email verification as an additional step after signing up. Unverified users shouold login but shouldn't be able to access the majority of the app's features
- [ ] Implement 2FA upon login, for users who requested that additional step
- [ ] Write appropriate documentation for resulting endpoints
- [ ] Implement appropriate error handling and responses
- [ ] Write comprehensive unit tests

### Definition of Done
- User is able to login after 2Factor Authentication
- User is able to verify their email
