### ISSUE TITLE
Feat: CRUD Sticky notes

### ISSUE THREAD

**Issue by jkarenzi** [jkarenzi/task-master-be#7]
### Description

As a user, I want to be able to create, get, update and delete a sticky note.

### Tasks

- [ ] Implement endpoints for managing sticky notes
- [ ] Write appropriate documentation for resulting endpoints
- [ ] Implement appropriate error handling and responses
- [ ] Write comprehensive unit tests

### Developer Notes

- Sticky notes should have an id, and content.
- Use of a rich text editor for content

### Definition of Done

- User is able to access endpoints for managing sticky notes
- Comprehensive unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation for the resulting endpoints is completed
